# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5cf800fadee63efc86e44a425130b6429d7d68ad382e094d3c0533ad4e62a3e971f2735f55cd34599fa3182abbe95ba2da0da896120b880416859db62512a0a
  MAILCHIMP_API_KEY: f3e0c9720c2c1e75a768cf6aa81a5397-us11
  MAILCHIMP_LIST_ID: "764952d5ba"

test:
  secret_key_base: 59aaee82a13a0c4bf2ca3b7f4bb6bacd640c529ec28f2055815b4ae8b71d72fdc6f5261c6909aa587694155949ab155b6dca437652824888c097a0900ef264ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  MAILCHIMP_API_KEY: f3e0c9720c2c1e75a768cf6aa81a5397-us11
  MAILCHIMP_LIST_ID: "764952d5ba"
